### PR TITLE
Directly publish /joint_state in ROS from kuka_driver.cc

### PR DESCRIPTION
**Pull request by peteflorence**
Only proposing merge into `master-rlg` branch but @sammy-tri maybe also useful for you

This seems to essentially solve the latency issue we were previously having with our robot state.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/13)

### CODE REVIEW

**Comment by sammy-tri** [comment]
I need to look a bit more at the internals, but my first thought is that I don't want to make ROS mandatory to compile the driver.  The simplest way might be to just surround the ROS code with `#ifdef IIWA_USE_ROS`...  will take a look at the changes in detail when I get a moment (hopefully later today).

**Comment by manuelli** [comment]
Hey @sammy-tri note that this is targeting `master-rlg` not `master.

**Comment by sammy-tri** [comment]
I think the ROS publish functionality could be useful for us at some point, but it would be inconvenient as a requirement now.  

Agree we're diverging by more than I'd like to see.  Perhaps I'll take a look at what would be needed to hand merge...  I didn't quite realize how long I'd been ignoring the situation.

**Comment by sammy-tri** [comment]
Looking at the state of the driver code again I guess I don't have much to add for this patch.  If we ever want to move it to master I guess we can make ROS optional then.  I opened #16 for the Sunrise 1.11 vs 1.13 compile issue, but I'm not sure what to do about the issue that we can't easily both use the same FRI git submodule (aside from perhaps not making it a submodule).

**Comment by peteflorence** [comment]
Thanks @sammy-tri I actually am just seeing your comments now on this -- my bad, must have missed the email notifications on it.

Anyway we are happy with the ROS functionality in this PR and agreed don't need to move it to master for now, but could in future.  Thanks!

**Pull request merged**
