### PR TITLE
Activate friction compensation in torque_only mode

### PR DESCRIPTION
**Pull request by AdityaBhat-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47)

### CODE REVIEW

**Comment by AdityaBhat-TRI** [comment]
+@sammy-tri for review.

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47)* status: all files reviewed, 2 unresolved discussions (waiting on @AdityaBhat-TRI)

___
*[`kuka-driver/kuka_driver.cc` line 554 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47#-NV6KnQaBlrRAhuCdWtG:-NV6KnQaBlrRAhuCdWtH:b-lzjrb0) ([raw file](https://github.com/RobotLocomotion/drake-iiwa-driver/blob/c076205ef72c38c6db72c8165176b549b8370475/kuka-driver/kuka_driver.cc#L554)):*
> ```cpp
>     
>     // IIR filter initialization with measured data (should be run always)
>     for( int i=0; i<numIIRCoeff+1; i++ ) {
> ```

nit: extra whitespace before/after parens
___
*[`kuka-driver/kuka_driver.cc` line 690 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47#-NV6KSUrCcw-KvauRq9w:-NV6KSUrCcw-KvauRq9x:b-k00gl8) ([raw file](https://github.com/RobotLocomotion/drake-iiwa-driver/blob/c076205ef72c38c6db72c8165176b549b8370475/kuka-driver/kuka_driver.cc#L690)):*
> ```cpp
>   // position. The gains are chosen so that it doesn't add energy into the
>   // system. Thanks to Johannes Lachner for providing this code(part of:
>   // https://github.com/jlachner/Explicit-FRI).
> ```

This link doesn't seem to go to a publicly available repo. Delete it or add some explanation here of what's in the repository instead of the link?

**Comment by AdityaBhat-TRI** [comment]
*[`kuka-driver/kuka_driver.cc` line 690 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47#-NV6KSUrCcw-KvauRq9w:-NVA-tyO9e7agtA5H9QO:buyhhpy) ([raw file](https://github.com/RobotLocomotion/drake-iiwa-driver/blob/c076205ef72c38c6db72c8165176b549b8370475/kuka-driver/kuka_driver.cc#L690)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This link doesn't seem to go to a publicly available repo. Delete it or add some explanation here of what's in the repository instead of the link?
</blockquote></details>

Based on my discussion with Johannes, the repo will be made public soon and he told me to add the link to it as a reference. I'll remove the reference for now. Will add it back after the repo is public.

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47)* status: all files reviewed, 2 unresolved discussions (waiting on @AdityaBhat-TRI)

___
*[`kuka-driver/kuka_driver.cc` line 690 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47#-NV6KSUrCcw-KvauRq9w:-NVWDSHr0UWViYbtrobV:b-8x60sb) ([raw file](https://github.com/RobotLocomotion/drake-iiwa-driver/blob/c076205ef72c38c6db72c8165176b549b8370475/kuka-driver/kuka_driver.cc#L690)):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

Based on my discussion with Johannes, the repo will be made public soon and he told me to add the link to it as a reference. I'll remove the reference for now. Will add it back after the repo is public.
</blockquote></details>

I think I'd be OK with a note stating that the repo is currently private but expected to be available publicly soon.  That along with the rest of the comment is probably OK.

**Comment by AdityaBhat-TRI** [comment]
*[`kuka-driver/kuka_driver.cc` line 690 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47#-NV6KSUrCcw-KvauRq9w:-NVZxb8kDeV8GY_tvYi0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-iiwa-driver/blob/c076205ef72c38c6db72c8165176b549b8370475/kuka-driver/kuka_driver.cc#L690)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think I'd be OK with a note stating that the repo is currently private but expected to be available publicly soon.  That along with the rest of the comment is probably OK.
</blockquote></details>

Done.

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47#-:-NVaK4knAYbYmiT6uzqD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AdityaBhat-TRI)

**Pull request merged**
