### PR TITLE
Build the driver with bazel

### PR DESCRIPTION
**Pull request by sammy-tri**
This is "my first bazel" type of work here.  There was a lot of cargo culting and trial and error.  Apologies for the parts I got wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/10)

### CODE REVIEW

**Comment by sammy-tri** [comment]
BTW most of the contents of tools was copied from drake directly, with the exception of `kuka-fri.BUILD`

+@siyuanfeng-tri for review/testing.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10#-:-Kw74UX4GFpQHK1IHMtR:b7gyzfc)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Reviewed 22 of 22 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/kuka-fri.BUILD, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10#-KwAqJM95WPtku15no0O:-KwAqJM95WPtku15no0P:bbf2tcr) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/e82ae9eefdf8046bb03a124f68c2491b81d4c8a8/tools/kuka-fri.BUILD#L29)):*
> ```
>         ],
>     #cmd = "echo $(location include/friClientApplication.h) $(location friClientApplication.h) $(location libFRIClient.a) $(location build/GNUMake/Makefile)",
>     cmd = "make -C external/kuka_fri/build/GNUMake &&" +
> ```

BTW this is basically calling make, and copy the stuff to somewhere else? 

---

*[tools/kuka-fri.BUILD, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10#-KwAsnMfhlXGNa_yOmGA:-KwAsnMgYbgO_LWMBOq8:bljkyl9) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/cbfc23e6dd256f5564ba05a1352cc2f235d637ce/tools/kuka-fri.BUILD#L28)):*
> ```
>         "friConnectionIf.h",
>         ],
>     #cmd = "echo $(location include/friClientApplication.h) $(location friClientApplication.h) $(location libFRIClient.a) $(location build/GNUMake/Makefile)",
> ```

BTW do you want to rm this line? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10#-:-KwAsulsb1gqbIW-zJds:bg7igkv)*

**Comment by sammy-tri** [comment]
Review status: 20 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/kuka-fri.BUILD, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10#-KwAqJM95WPtku15no0O:-KwAtT_3gl1hj8gob4df:b5hbdjo) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/e82ae9eefdf8046bb03a124f68c2491b81d4c8a8/tools/kuka-fri.BUILD#L29)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW this is basically calling make, and copy the stuff to somewhere else? 
</blockquote></details>

(resolved f2f)

---

*[tools/kuka-fri.BUILD, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10#-KwAsnMfhlXGNa_yOmGA:-KwAtRvqC2-EcISDjK1O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/cbfc23e6dd256f5564ba05a1352cc2f235d637ce/tools/kuka-fri.BUILD#L28)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW do you want to rm this line? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/10)*

**Pull request merged**
