### PR TITLE
Find drake lcmtypes interface library

### PR DESCRIPTION
**Pull request by fbudin69500**
This project requires some lcm types from drake but that dependency was not explicit.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/4)

### CODE REVIEW

**Comment by fbudin69500** [comment]
@sammy-tri : This is the follow-up of [this previous PR](https://github.com/RobotLocomotion/drake-iiwa-driver/commit/1eaccc24b316e63c97dd13ba695227417d3200d8)

**Comment by sammy-tri** [comment]
Works for me with the current drake CMake build.  It looks like it should with with the installed bazel-build drake artifacts too from my first glance, but I haven't tested it (since I'm still not sure how to build the intended results).  Is it believed to work in that scenario too?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/4#-:-KppfpY8cIW0SvgPjzzi:bm6zt50)*

**Comment by fbudin69500** [comment]
Indeed, the scenario which lead me to update these files is when bazel-build drake, which is what I have tested it with on my computer.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/4#-:-KpqKdZ5il0OInT-tHZS:b-q3c6xa)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-iiwa-driver/4#-:-Kpqi_uwLbQ8kORqR5Dq:bnfp4nl)*

**Pull request merged**
