### PR TITLE
[kuka_driver] Add --torque_only flag

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Tested on hardware for non-zero "hold" gains and zero "hold" gains (reproducing gravity comp demo)

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for review, please (after #43)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-:-NGZEI8s8zDiPC5J67Of:brbl3yp)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGZEGiZAForch5SqtPZ:-NGZEGiZAForch5SqtP_:b-99dpzy) (no related file):*
Working: Requires #43

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb7to6AQSy1g6wA7BO:-NGb7to78clbNImcLxw7:b5l7p63) (no related file):*
Working: Testing a bit more on hardware. Needs updates.

___
___
*[`kuka-driver/kuka_driver.cc` line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb7xM60dBh8qOu0tvr:-NGb7xM60dBh8qOu0tvs:bb4s7w0) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/41b06388859ff36c53c0b3cd71f7f92940cc9158/kuka-driver/kuka_driver.cc#L110)):*
> ```cpp
> DEFINE_double(
>     torque_only_kd_scale, 1.0,
>     "Scaling for velocity gains when inactive.");
> ```

Working: Will add expiration flag to reengage holding controller.
___
*[`kuka-driver/kuka_driver.cc` line 581 at r1](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb80y-8gMJvUnPqJ1F:-NGb80y-8gMJvUnPqJ1G:b-ejjg5u) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/41b06388859ff36c53c0b3cd71f7f92940cc9158/kuka-driver/kuka_driver.cc#L581)):*
> ```cpp
>       bool command_valid = lcm_client_->GetTorqueCommand(robot_id_, torque);
>       if (inhibit_motion_in_command_state_ || !command_valid) {
>         // Position control holding current position.
> ```

Working: When doing holding controller, `joint_position_when_command_entered_` will need to be updated due to mode switch. This will happen given command expiration.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGZEGiZAForch5SqtPZ:-NGbAQnr-IjwnfEIQJSn:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires #43
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb7to6AQSy1g6wA7BO:-NGbARXaAhj92oYjBHb1:b-jqmlqi) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Testing a bit more on hardware. Needs updates.
</blockquote></details>

Can switch between gravity comp (sending zero torques) and switch to hold controller when I kill the robot hub controller.
Going to test more complex controllers (inverse dynamics in joint space, operational space w/ null space)

___
___
*[`kuka-driver/kuka_driver.cc` line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb7xM60dBh8qOu0tvr:-NGbAN4t1jikYEY8L24p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/41b06388859ff36c53c0b3cd71f7f92940cc9158/kuka-driver/kuka_driver.cc#L110)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will add expiration flag to reengage holding controller.
</blockquote></details>

Done.
___
*[`kuka-driver/kuka_driver.cc` line 581 at r1](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb80y-8gMJvUnPqJ1F:-NGbAO1PEc4Nba91wTcu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/41b06388859ff36c53c0b3cd71f7f92940cc9158/kuka-driver/kuka_driver.cc#L581)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: When doing holding controller, `joint_position_when_command_entered_` will need to be updated due to mode switch. This will happen given command expiration.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb7to6AQSy1g6wA7BO:-NGbFuBG3kBCbVZTse37:b-o40igf) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can switch between gravity comp (sending zero torques) and switch to hold controller when I kill the robot hub controller.
Going to test more complex controllers (inverse dynamics in joint space, operational space w/ null space)
</blockquote></details>

Ran joint-space inverse dynamics (pydrake robot hub), but alas, just like the Panda the IIWA itself doesn't seem to accommodate friction / rotor inertia / whatever at the 3 more distal axes (A5, A6, A7).
So, will mark it as "working, but needs tuning", which can be done outside of this driver.

Will tune just a bit, then run the operation space controller.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGb7to6AQSy1g6wA7BO:-NGbXRJM-bCtybxTiC7y:b-ugj6jz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ran joint-space inverse dynamics (pydrake robot hub), but alas, just like the Panda the IIWA itself doesn't seem to accommodate friction / rotor inertia / whatever at the 3 more distal axes (A5, A6, A7).
So, will mark it as "working, but needs tuning", which can be done outside of this driver.

Will tune just a bit, then run the operation space controller.
</blockquote></details>

Done. Posted internal TRI video of doing operational space control on IIWA.

The models are weird, but that's a separate issue from the driver.

___

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`kuka-driver/kuka_driver.cc` line 607 at r2](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGxKPqN96yfSsXg3yZ3:-NGxKPqN96yfSsXg3yZ4:baemiyx) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/560164158382a2cbd7ec4ab93e3fe69f0e3cc4bf/kuka-driver/kuka_driver.cc#L607)):*
> ```cpp
>           warned_about_expiration_ = true;
>         }
>       } else {
> ```

Should this be `else if (command_valid)`?  (AFAICT a command can be invalid but not expired)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @sammy-tri)

___
*[`kuka-driver/kuka_driver.cc` line 607 at r2](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-NGxKPqN96yfSsXg3yZ3:-NH6MLga6TYYZz2Ea-Mx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/560164158382a2cbd7ec4ab93e3fe69f0e3cc4bf/kuka-driver/kuka_driver.cc#L607)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this be `else if (command_valid)`?  (AFAICT a command can be invalid but not expired)
</blockquote></details>

Done.

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44#-:-NH6OLi_EQqMb7W8PFvW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
