### PR TITLE
Update drake; update minor conventions and use linting

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/43)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/43#-:-NGZE1HUEHRAecwDPzVZ:b-89l999)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @sammy-tri)

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/43#-:-NGb6NKI6Rlrlkq8vSAM:bnfp4nl)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`.bazelrc` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/43#-NGb4fVc32ituy4SjLJc:-NGb4fVc32ituy4SjLJd:b-gehqb9) ([raw file](https://github.com/robotlocomotion/drake-iiwa-driver/blob/bc6b16b5deb76bca9baaa295d435e9c8ddf56ba2/.bazelrc#L37)):*
> ```
> 
> # Default build options.
> build --force_pic=yes
> ```

BTW this seems like it can't possibly be useful here, but it's probably not doing harm (and I assume was cargo culted from drake (and anzu where I still have my doubts about its correct usage in some places)).

**Review by sammy-tri — APPROVED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/43)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by sammy-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
> BTW this seems like it can't possibly be useful here, but it's probably not doing harm (and I assume was cargo culted from drake (and anzu where I still have my doubts about its correct usage in some places)).

Yup, just cargo-culted from either Anzu or `drake-external-examples`.

I believe our usage of `--force_pic=yes` in Anzu makes our Python bindings much easier by admitting simpler relinking I introduced a couple of months ago.
Said another way: I dunno if it strictly helps, but yeah, ain't too keen on testing that any time soon.

**Pull request merged**
